<a href="https://colab.research.google.com/github/MinYeongPark/AI_practice/blob/main/221017%EC%8B%A4%EC%8A%B5_3_%EC%9D%B8%EA%B3%B5_%EC%8B%A0%EA%B2%BD%EB%A7%9D%EC%9D%84_%ED%95%99%EC%8A%B5%ED%95%98%EB%8A%94_%EB%B0%A9%EB%B2%95(%EC%97%AD%EC%A0%84%ED%8C%8C).ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

import torch
import torch.nn as nn

### 역전파 : 가중치 업데이트

In [ ]:
torch.manual_seed(1017) 

inputs = torch.randn(2, 2) # 2행 2열로 이루어진 데이터를 임시로 생성
inputs

tensor([[-0.4318,  0.0749],
        [-0.1667, -1.6542]])

In [ ]:
torch.manual_seed(777) 

targets = torch.randn(2) # 각 행마다 해당하는 label을 생성
targets

tensor([-0.4015, -0.5934])

In [ ]:
# 사용할 네트워크를 생성

torch.manual_seed(1017)

total_network = nn.Sequential(  
    nn.Linear(2, 1), 
    nn.Sigmoid()
)

total_network[0].weight

Parameter containing:
tensor([[0.4371, 0.3060]], requires_grad=True)

In [ ]:
# 가중치 업데이트에 필요한 요소들 설정 : 뒤에가서 하나씩 살펴볼 예정, 지금은 이런게 있어야 업데이트가 되는구나 정도로 이해
learning_rate = 0.001
criterion = nn.MSELoss() # MSE : 정답과의 차이를 제곱
optimizer = torch.optim.Adam(total_network.parameters(), lr=learning_rate)

In [ ]:
total_network.train() # 만들어진 네트워크를 학습 모드로 설정

pred = total_network(inputs) # 네트워크에 아까 생성해 두었던 2행 2열의 데이터를 입력
print(pred) # 입력값은 행별로 들어가고, 이에 대한 network의 결과를 출력

loss = criterion(inputs, pred) # network의 결과를 실제 label과 비교하여 loss를 구함
print(loss)

tensor([[0.5068],
        [0.4047]], grad_fn=<SigmoidBackward0>)
tensor(1.4082, grad_fn=<MseLossBackward0>)


In [ ]:
loss.backward() # loss값을 참고하여 각 가중치에 대해 편미분 
optimizer.step() # 편미분된 값과 학습률을 통해 한 스텝 최적화

In [ ]:
total_network[0].weight # 한번 역전파가 이루어지고 나서 모델의 가중치가 업데이트 된걸 확인 가능
                        # 첫번째 층?을 가리키기 위해 0이라고 둠

Parameter containing:
tensor([[0.4381, 0.3070]], requires_grad=True)

In [ ]:
pred = total_network(inputs) 
print(pred)

loss = criterion(inputs, pred) 
print(loss) # 한번 역전파가 이루어지고 나서 loss가 줄어 들은 것을 확인 

tensor([[0.5064],
        [0.4040]], grad_fn=<SigmoidBackward0>)
tensor(1.4071, grad_fn=<MseLossBackward0>)


In [ ]:
# optimizer와 loss function에 대한 차이는 이후에